{
 "title": "Data Trans Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "IP",
    "label": "IP",
    "query": "select ip from t_data_receive_log;"
   }
  ]
 },
 "panels": [
  {
   "title": "IP Receive Data Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(uuid) from t_kr_capture\n"
    }
   ]
  },
  {
   "title": "Receive Data Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time as \"시간\", sno as \"카메라\" , distance as \"길이\", filename as \"파일이름\", absPath as \"파일경로\"  from t_kr_capture;"
    }
   ]
  },
  {
   "title": "IP Receive Data Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(dataLength) from t_data_receive_log\n"
    }
   ]
  },
  {
   "title": "Receive Data Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT time as \"시간\", ip as \"아이피\" , dataLength as \"데이터 길이\", dataDetail as \"받은데이터\"  from t_data_receive_log"
    }
   ]
  },
  {
   "title": "IP Send Data Total",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(dataLength) from t_data_send_log\n"
    }
   ]
  },
  {
   "title": "Send Data Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT time as \"시간\", ip as \"아이피\" , dataLength as \"데이터 길이\", dataDetail as \"보낸데이터\"  from t_data_send_log"
    }
   ]
  }
 ]
}